### ISSUE TITLE
Download not working in Edge and IE

### ISSUE THREAD

**Issue by phit** [SpongePowered/Ore#222]
Reported on the forums https://forums.spongepowered.org/t/skyclaims/16861/18

Browser & Version: `Edge, IE11`

Operating System: `Windows 10`

Steps to reproduce:

* try to download anything that's not approved on Ore
* get to this screen http://i.imgur.com/nhxLfbH.png
* continue doesn't work

**Comment by windy1** [comment]
Fixed in 824b5e93805c15164019568b91b9ca1535440732

**Comment by FirEmerald** [comment]
It is either not fixed or un-fixed, since I'm having that exact issue now.

**Comment by windy1** [comment]
Still happening because the confirmation form is detached from the submit button apparently something Edge and IE will not play nice with.

**Comment by windy1** [comment]
Fixed in f9c89ad0390dd82965124ddc7184881ac4660388
