### ISSUE TITLE
Logging into Ore fails

### ISSUE THREAD

**Issue by Flibio** [SpongePowered/Ore#45]
Whenever I press the login button on Ore site, there is an exception in the code. The exception id is `6pkocd6b9`. I am logged in on the forums when I try to login to Ore, so that is not the cause.

**Comment by windy1** [comment]
This should be fixed as of https://github.com/SpongePowered/Ore/commit/24d3767847c2c045a6ed6aa54748a41576f5a397

**Comment by Flibio** [comment]
@windy1 It still doesn't appear to work for me, the exception id this time is `6pkpcjipb`. I've tried it in other browsers as well.

**Comment by windy1** [comment]
Ah I believe I found the actual issue. Should be fixed now.
