### ISSUE TITLE
Markdown Formatting Issues

### ISSUE THREAD

**Issue by MichaelFedora** [SpongePowered/Ore#84]
### On headers:
# `#` Every
###### `######` but they do on ore.

My problem with this is when things get _really_ messy, such as [on my home page](https://ore-staging.spongepowered.org/MichaelFedora/Fedora's-Economy/pages/Home), with lines _everywhere_, (but not on [github](https://github.com/MichaelFedora/FedorasEconomy/blob/master/README.md), for comparison).

Also, every header in Github style is at least bolded, whereas the ones on Ore are not (and can get confusing with regular text).
### On tables:

Their a little gross, but at least their implemented (I'm looking at you, sponge forums). It would be nice to get them similar to github as well ^_^

[Link for tables (and more confusing headers)](https://ore-staging.spongepowered.org/MichaelFedora/Fedora's-Economy/pages/Commands).
### On inline code:

It's red. Could we a _least_ have it orange? :stuck_out_tongue: Though I think the standard `grey` would be good too, it's up to you.
### On line-separators

Github has an interesting way of doing two of them:

`---`

---

`--`
## 

Only the triple works for the other symbols:

`***`

---

`___`

---

In addition, putting dashes (or whatever) right above a text, according to github, should still be a linebreak, regardless of the symbol (weird I know). It's up to you whether or not you want to implement this, because I had (have) to fix my readme's so I can copy-pasta to ore/the forums :stuck_out_tongue: 

```

---
text
```

---

text
### Lastly, the preview

... is different from what is saved. Tables don't work and headers don't have the proper underlines. Otherwise it seems to work good :wink:

Thanks for your hard work!

**Comment by ryantheleach** [comment]
https://github.com/SpongePowered/Ore/issues/35

**Comment by windy1** [comment]
Ok, everything on here should be resolved now besides the line separators.

**Comment by MichaelFedora** [comment]
They look _beautiful_. Well done, and thanks Windy :heart:

However, I still have a _small_ problem with the headers: their still not bolded and even go _smaller_ than the normal text (at h6). This size-issue is still the same case with SpongeForums, though they are bolded at least.

You can check out a test page [here](https://ore-staging.spongepowered.org/MichaelFedora/Fedora's-Economy/pages/testmarkdown).

**Comment by Zidane** [comment]
@windy1 

I can confirm, looks a lot better now. Any chance of implementing checkboxes?

**Comment by windy1** [comment]
Checkboxes have been in for a bit now. Gonna close this now unless anyone has more to add.
